account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('registration/', views.sign_up, name='account-sign_up'),
    path('login/', views.sign_in, name='account-sign_in'),
    path('logout/', views.sign_out, name='account-sign_out'),
]

company/urls.py
from django.urls import path
from . import views

app_name = "company"

urlpatterns = [
    path('', views.CompanyList.as_view(), name='company-list'),
    path('add/', views.CompanyCreate.as_view(), name='company-add'),
    path('update/<int:pk>', views.CompanyUpdate.as_view(), name='company-update'),
    path('delete/<int:pk>', views.CompanyDelete.as_view(), name='company-delete'),
    path('detail/<int:pk>', views.CompanyDetail.as_view(), name='company-detail'),
]

django_company/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('company/', include('company.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

templates/partials/_message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" id="alert_box">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times</button>
            {{ message }}
        </div>
    {% endfor %}
    <script>
    let stIdAndFadeOut = setTimeout(function() {
        $('#alert_box').fadeOut();
    }, 5000);
    </script>
{% endif %}

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <!-- Navbar brand -->
    <a href="{% url 'main:index' %}" class="navbar-brand">Company</a>

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'main:index' %}">Home</a></li>
        {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'company:company-list' %}">Company</a></li>
        {% endif %}
    </ul>
    <ul class="navbar-nav justify">
        {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link font-weight-bold text-danger"
                                    href="{% url 'main:index' %}">Welcome {{ user.first_name }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'account:account-sign_out' %}">Logout</a></li>
        {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'account:account-sign_up' %}">Sign Up</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'account:account-sign_in' %}">Sign In</a></li>
        {% endif %}
    </ul>
</nav>