company/urls.py
from django.urls import path
from . import views

app_name = "company"

urlpatterns = [
    path('', views.CompanyList.as_view(), name='company-list'),
    path('add/', views.CompanyCreate.as_view(), name='company-add'),
    path('update/<int:pk>', views.CompanyUpdate.as_view(), name='company-update'),
    path('delete/<int:pk>', views.CompanyDelete.as_view(), name='company-delete'),
    path('detail/<int:pk>', views.CompanyDetail.as_view(), name='company-detail'),
]

django_company/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('company/', include('company.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

company/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Company(models.Model):
    id = models.BigAutoField(verbose_name='ID', primary_key=True)
    brand = models.CharField(verbose_name='Brand', unique=True, max_length=200)
    city = models.CharField(verbose_name='City', max_length=200)
    street = models.CharField(verbose_name='Street', max_length=200)
    account_number = models.CharField(verbose_name='Account Number', max_length=200, unique=True)
    image_logo = models.ImageField(upload_to='companies', blank=True)
    created_at = models.DateTimeField(verbose_name='Created At', editable=False)
    updated_at = models.DateTimeField(verbose_name='Updated At', editable=False)

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def get_absolute_url(self):
        return reverse('company:company-detail', kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        """ On Save, update timestamps """
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Company, self).save(*args, **kwargs)

    def __str__(self):
        return self.brand

company/forms.py
from django.forms import ModelForm
from . import models


class CompanyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        self.fields['brand'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['city'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['street'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['account_number'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['image_logo'].widget.attrs = {
            'class': 'form-control'
        }

    class Meta:
        model = models.Company
        fields = ['brand', 'city', 'street', 'account_number', 'image_logo']

company/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from .models import Company
from .forms import CompanyForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


class CompanyCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """ View to add a new company to the database """
    model = Company
    form_class = CompanyForm
    template_name = "company/company_add.html"
    extra_context = {
        'page_title': "Company - Create Form",
    }
    raise_exception = True
    success_message = "Company created successfully"


class CompanyList(LoginRequiredMixin, ListView):
    """ View to list all existing Companies """
    model = Company
    template_name = "company/company_list.html"
    extra_context = {
        'page_title': "Company - List",
    }
    paginate_by = 10
    queryset = Company.objects.order_by('-brand')
    context_object_name = 'company_list'
    raise_exception = True


class CompanyDetail(LoginRequiredMixin, DetailView):
    """ View to get details about a company """
    model = Company
    template_name = "company/company_detail.html"
    extra_context = {
        'page_title': "Company - Details",
    }
    raise_exception = True
    context_object_name = 'company_single'


class CompanyUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """ View to update a companies data """
    model = Company
    template_name = "company/company_update.html"
    extra_context = {
        'page_title': "Company - Update Form",
    }
    form_class = CompanyForm
    raise_exception = True
    success_message = "Company updated successfully"


class CompanyDelete(LoginRequiredMixin, DeleteView):
    """ View to delete an existing company """
    model = Company
    template_name = "company/company_delete.html"
    context_object_name = 'company_single'
    raise_exception = True
    success_message = "Company was deleted successfully"
    success_url = reverse_lazy('company:company-list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(CompanyDelete, self).delete(request, *args, **kwargs)

company/templates/company/company_add.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form class="mt-4" action="" enctype="multipart/form-data" method="post">
            <h4>Create a new company</h4>
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.brand.errors }}
                <label for="{{ form.brand.id_for_label }}">Brand:</label>
                {{ form.brand }}
            </div>
            <div class="form-group">
                {{ form.city.errors }}
                <label for="{{ form.city.id_for_label }}">City:</label>
                {{ form.city }}
            </div>
            <div class="form-group">
                {{ form.street.errors }}
                <label for="{{ form.street.id_for_label }}">Street:</label>
                {{ form.street }}
            </div>
            <div class="form-group">
                {{ form.account_number.errors }}
                <label for="{{ form.account_number.id_for_label }}">Account Number:</label>
                {{ form.account_number }}
            </div>
            <div class="form-group">
                {{ form.image_logo.errors }}
                <label for="{{ form.image_logo.id_for_label }}">Logo:</label>
                {{ form.image_logo }}
            </div>
            <input class="btn btn-info" type="submit" value="Create">
        </form>
        <!-- Button to return to the company list -->
        <a href="{% url 'company:company-list' %}">
            <button class="btn btn-primary mt-4">Back to Companies</button>
        </a>
    </div>
{% endblock %}

company/templates/company/company_delete.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
    <form action="" method="post">
    <h4>Delete a company</h4>
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock content %}

company/templates/company/company_detail.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
    <section id="showcase-inner" class="py-2">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">{{ company_single.brand }}</h1>
                    <p class="lead">
                        {{ company_single.city }}, {{ company_single.street }}, {{ company_single.account_number }}
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section id="company" class="py-4">
        <div class="container">
            <a href="{% url 'company:company-list' %}">
                <button class="btn btn-light mb-4">Back to Companies</button>
            </a>
            <div class="row">
                <div class="col-md-6">
                    {% if company_single.image_logo %}
                        <img class="img-fluid mb-3" src="{{ company_single.image_logo.url }}" alt="logo">
                    {% else %}
                        <img class="img-fluid mb-3"
                             src="{% static 'company/img/noimage.png' %}" alt="nologo">
                    {% endif %}
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item text-secondary">Company Brand:
                            <span class="float-right">{{ company_single.brand }}</span>
                        </li>
                        <li class="list-group-item text-secondary">City:
                            <span class="float-right">{{ company_single.city }}</span>
                        </li>
                        <li class="list-group-item text-secondary">Street:
                            <span class="float-right">{{ company_single.street }}</span>
                        </li>
                        <li class="list-group-item text-secondary">Account Number:
                            <span class="float-right">{{ company_single.account_number }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

company/templates/company/company_list.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <!-- Add new company -->
        <a href="{% url 'company:company-add' %}">
            <button class="btn btn-primary mt-4">Add</button>
        </a>

        <!-- Table with companies data -->
        {% if object_list %}
            <table class="table mt-1">
                <thead class="table-dark">
                <tr>
                    <th>LOGO</th>
                    <th>Brand</th>
                    <th>City</th>
                    <th>Street</th>
                    <th>Account Number</th>
                    <th>Function</th>
                </tr>
                </thead>
                <tbody>
                {% for company in company_list %}
                    <tr>
                        {% if company.image_logo %}
                            <td><img class="img-main img-fluid mb-3" src="{{ company.image_logo.url }}" alt="logo"
                                     width="220" height="60"></td>
                        {% else %}
                            <td><img class="img-main img-fluid mb-3"
                                     src="{% static 'company/img/noimage.png' %}" alt="nologo" width="100" height="60">
                            </td>
                        {% endif %}
                        <td><a href="{{ company.get_absolute_url }}">{{ company.brand }}</a></td>
                        <td>{{ company.city }}</td>
                        <td>{{ company.street }}</td>
                        <td>{{ company.account_number }}</td>
                        <td>
                            <a href="{% url 'company:company-update' company.id %}">Update |</a>
                            <a href="{% url 'company:company-delete' company.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No companies yet</p>
        {% endif %}

        <!-- Pagination -->
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_other_pages %}
                    <li class="page-item">
                        <a href="/company/?page=1" class="page-link text-black-50">&laquo; first</a>
                    </li>
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="/company/?page={{ page_obj.previous_page_number }}">previous</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" onclick="return false" href="">previous</a>
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link text-danger" href="#" disabled="True">{{ page_obj.number }}</a>
                    </li>
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="/company/?page={{ page_obj.next_page_number }}">next</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" onclick="return false" href="">next</a>
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link text-black-50" href="/company/?page={{ page_obj.paginator.num_pages }}">Last
                            &raquo;</a>
                    </li>
                    </ul>
                {% endif %}
        {% endif %}

        <!-- Button to return to home -->
        <a href="{% url 'main:index' %}">
            <button class="btn btn-primary">Back to home</button>
        </a>
    </div>
{% endblock %}

company/templates/company/company_update.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <form class="mt-4" action="" enctype="multipart/form-data" method="post">
            <h4>Update information about a company</h4>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Confirm">
        </form>
        <!-- Button to return to the company list -->
        <a href="{% url 'company:company-list' %}">
            <button class="btn btn-primary mt-4">Back to Companies</button>
        </a>
    </div>
{% endblock %}